### ISSUE TITLE
document data handling

### ISSUE THREAD

**Issue by simboonlong** [TradeTrust/document-creator-website#256]
The way document data in forms are handled (lots of data wrangling around) needs to be revisited as there are quite a number of permutations:
- OA v2 document.
  - verifiable.
  - transferable.
- OA v3 document. (related [pr](https://github.com/Open-Attestation/tutorial-renderer/pull/1) on how should we approach VC data shape, no conclusion yet)
  - verifiable.
  - transferable. 
- OA DID document.
  - verifiable.

Exception handlings:
- The additional of `ownership` data field for EBL document, set in [setCurrentFormOwnership](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L109-L112).
- `network` should not be necessary in config file for DID documents.

Affected user flows of:
1. data file upload flow - single document, data populated by json file:
    - mergeFormValue of [single document flow](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx#L85-L90).
    - [setCurrentForm](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L120-L142).
2. data file upload flow - multiple documents, data populated by csv file:
    - mergeFormValue of [mulitple documents flow](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx#L82-L84).
    - [newPopulatedForm](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L76-L92).
3. user input flow - single document, data manually filled by user:
    - [setFormData](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx#L153).
    - [setCurrentFormData](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicFormLayout.tsx#L172).
    - [setCurrentForm](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L120-L142). (same as point 1)
4. user freshly adding new form:
    - [onAddNewForm](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicFormLayout.tsx#L74-L79).
    - [newForm](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L53-L65).
5. user upload attachments:
    - [setAttachments](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx#L95-L101).
6. user rename document file name:
    - [handleChangeFileName](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicForm/DynamicForm.tsx#L62-L76).
    - [setCurrentFileName](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/common/context/forms/index.tsx#L114-L117).
7.  document preview functionality for v2, v3 documents.
    - [currentUnwrappedData](https://github.com/TradeTrust/document-creator-website/blob/8adc3396c2bd28a4e48ef68952c254d1b8f0eea1/src/components/DynamicFormContainer/DynamicFormLayout.tsx#L116).

**Comment by tradetrustimda** [comment]
Closing this due to irrelevancy.
