### ISSUE TITLE
malformed wallet

### ISSUE THREAD

**Issue by blockchain-sg** [TradeTrust/document-creator-website#8]
Getting malformed wallet error when uploading the attached file
![malformed_wallet](https://user-images.githubusercontent.com/66362752/83627114-08a10000-a5c9-11ea-8980-431d0e3195d9.JPG)

[sample_document_1.txt](https://github.com/TradeTrust/document-creator-website/files/4722688/sample_document_1.txt)

**Comment by B-SG** [comment]
Using the sample config from configurable-dapp project (https://raw.githubusercontent.com/TradeTrust/configurable-dapp/master/src/test/fixture/config.json), getting different error now.
![malformed_wallet1](https://user-images.githubusercontent.com/66362752/83733577-4b71df00-a680-11ea-8634-7daf58c56f84.JPG)

**Comment by AmirZaini** [comment]
currently having the same error as well. Have you found a fix to this?

**Comment by B-SG** [comment]
Not yet.

**Comment by simboonlong** [comment]
the errors are self explanatory

can refer to docs on how to create your own config file -> https://docs.tradetrust.io/docs/document-creator/config-file/file-structure

a sample file looks something like this -> https://github.com/TradeTrust/document-creator-website/blob/master/src/test/fixtures/sample-config-local.json
