### ISSUE TITLE
npm run start fails on windows

### ISSUE THREAD

**Issue by AmirZaini** [TradeTrust/document-creator-website#9]
For windows users using visual studio code if you are getting errors that sleep is not an internal or external command. Locate package.json, scripts and remove sleep 2 && in start:js
![image](https://user-images.githubusercontent.com/66545662/83991017-0f8b9200-a97e-11ea-80b8-13342953de66.png)

**Comment by yehjxraymond** [comment]
This repository is not in general availability. We will not be providing support to run this service until it is ready.

May i know what you are trying to achieve by running this repo though?

**Comment by AmirZaini** [comment]
I'm trying to understand the Tradetrust protocol as I would like to try and do integration with it to a blockchain project that I'm working on to better understand the possibilities of document storage within blockchain.

**Comment by yehjxraymond** [comment]
None of our code stores the document on the blockchain. Feel free to implement any type of object storage for your project. Will be closing this issue.
